name: Docker Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Prometheus image
      run: |
        cd prometheus
        docker build -t prometheus-test .
        
    - name: Build Grafana image
      run: |
        cd grafana
        docker build -t grafana-test .
        
    - name: Test Docker Compose
      run: |
        docker-compose config
        
    - name: Cleanup
      run: |
        docker system prune -f
